import cv2
img=cv2.imread('logo.jpg',0)
resize_img=cv2.resize(img,(200,200))
half_size=cv2.resize(img,(0,0),fx=0.5,fy=0.5)
rotated_img=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
cv2.imshow('Image1',resize_img)
cv2.imshow('Image2',half_size)
cv2.imshow('Image3',rotated_img)
cv2.imwrite('new_img.jpg',rotated_img)
cv2.waitKey(0)
cv2.destroyAllWindows()